name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        flutter-version: [3.24.1]  # Update to the Flutter version your project uses

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
        env:
          LANG: C.UTF-8

      # Optional: iOS build step, only runs on macOS runners
      - name: Build iOS App
        if: runner.os == 'macOS'
        run: flutter build ios --release
        env:
          LANG: C.UTF-8

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.0.0

  #     - name: Install Dependencies
  #       run: flutter pub get

  #     # Example deployment step for Firebase
  #     - name: Deploy to Firebase
  #       if: success()
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #       run: |
  #         flutter build web
  #         firebase deploy --only hosting
